kind: pipeline
type: docker
name: simulate-block-broadcast

trigger:
  event: [ push ]
  branch: [ improvement/message-order ]

steps:

- name: publish-image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: openmina/mina-network-debugger
    tags:
      - message-order
    password:
      from_secret: docker_hub_password
    username:
      from_secret: docker_hub_username

- name: deploy
  image: alpine/helm:3.8.1
  volumes:
    - name: test-result
      path: /test
  environment:
    DRONE_KUBECONFIG:
      from_secret: k8s_config
  commands:
    - mkdir -p $HOME/.kube
    - echo "$DRONE_KUBECONFIG" > $HOME/.kube/config
    # - kubectl -n test-debugger delete job mock
    - helm upgrade mina-debugger-test helm/tester --values=helm/tester/values.yaml --namespace=test-debugger --set=build_number=${DRONE_BUILD_NUMBER} --set=blocks=$BLOCKS --set=delay=$DELAY --set=parallelism=$PARALLElISM --set=image.tag=message-order
    - apk update && apk add curl
    - sleep $(( $BLOCKS * $DELAY ))
    - while [ $(curl -s $URL) == "null" ]; do sleep 1; done
    - curl -s $URL > /test/test.json

- name: test-ipc-matches
  image: alpine:3.17.2
  volumes:
    - name: test-result
      path: /test
  commands:
    - apk update && apk add jq
    - if [[ $(jq .ipc_ok /test/test.json) == "true" ]]; then exit 0; else exit 1; fi

- name: test-connections-same-as-tcpflow
  image: alpine:3.17.2
  volumes:
    - name: test-result
      path: /test
  commands:
    - apk update && apk add jq
    - if [[ $(jq .connections_ok /test/test.json) == "true" ]]; then exit 0; else exit 1; fi

- name: test-connections-order
  image: alpine:3.17.2
  volumes:
    - name: test-result
      path: /test
  commands:
    - apk update && apk add jq
    - if [[ $(jq .connections_order_ok /test/test.json) == "true" ]]; then exit 0; else exit 1; fi

- name: test-database-messages-order-and-timestamp-filter
  image: alpine:3.17.2
  volumes:
    - name: test-result
      path: /test
  commands:
    - apk update && apk add jq
    - if [[ $(jq .db_order_ok /test/test.json) == "true" ]]; then exit 0; else exit 1; fi

- name: test-all-events-stores
  image: alpine:3.17.2
  volumes:
    - name: test-result
      path: /test
  commands:
    - apk update && apk add jq
    - if [[ $(jq .db_events_ok /test/test.json) == "true" ]]; then exit 0; else exit 1; fi

environment:
  BLOCKS: 20
  DELAY: 6
  PARALLElISM: 10
  URL: http://1.k8.openmina.com:31876/test

volumes:
- name: test-result
  temp: {}
